
language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t nicolaslazzos/docker-ci-cd -f Dockerfile.dev . 

script:
  - docker run -e CI=true nicolaslazzos/docker-ci-cd npm run test:ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-ci-cd"
  env: "Dockercicd-env"
  bucket_name: "elasticbeanstalk-us-east-1-161028048438"
  bucket_path: "docker-ci-cd"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY